name: Test Deployment to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-powershell-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy PowerShell Modules to ACR
        uses: ethorneloe/deploy-ps-modules-to-acr@main
        with:
          acr-name: ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME}}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME}}
          module-source-path: "./powershell/modules"
