name: Test Context var in custom action

on:
  workflow_dispatch:

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test context
        uses: ./.github/custom-actions/test
