name: Test Context var in custom action

on:
  workflow_dispatch:

jobs:
  deploy_test:
    name: deploy_test
    runs-on: ubuntu-latest
    environment: 'test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test context - custom action
        uses: ./.github/custom-actions/test

      - name: Get job name
        run: |
          # Both work:
          echo "Job name is $GITHUB_JOB"
          echo "How about ${{ github.jobs[deploy_test].name }}"
