name: Test Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-powershell-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Test AzCopy login
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_CONTAINER_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
        run: |
          
          $storageAccountName = '${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}'
          $storageAccountContainerName = '${{ secrets.AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}'
          $tenantId = '${{ secrets.AZURE_TENANT_ID }}'
        
          $Env:AZCOPY_AUTO_LOGIN_TYPE="AZCLI"
          $Env:AZCOPY_TENANT_ID=$tenantId
          pwd
          azcopy copy "./powershell/modules/" "https://$storageAccountName.blob.core.windows.net/$storageAccountContainerName" --overwrite=false --recursive=true
        shell: pwsh
