name: Test Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy PowerShell Modules to Azure Storage
        uses: ethorneloe/deploy-ps-modules-to-azure-storage@main
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          storage-account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          storage-account-container-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}
          repo-powershell-module-path: "./powershell/modules"
