name: PowerShell Composite Action CI

on:
  workflow_dispatch:
  
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: run script
        run: |
          write-host "Test"
        shell: pwsh
  job2:
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: run script 2
        run: |
          write-host "Test2"
        shell: pwsh
